version: "3"

services:
  redis:
    image: redis
    ports:
      - "0.0.0.0:16379:6379"
    container_name: redis-16379

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=root"
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    container_name: mysql-13306

  zookeeper:
    image: zookeeper
    ports:
      - "0.0.0.0:12181:2181"

volumes:
  mysql:
