version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  wordpress:
    image: wordpress
    ports:
      - "1218:80"
    links:
      - mysql
  hexo:
    image: mgary34/nginx-hexo
    ports:
      - "80:80"
    environment:
      GITREPO: https://github.com/gary34/mgary.cc.git